### ISSUE TITLE
"SyntaxError: Unexpected token � " caused by serialized Celery response

### ISSUE THREAD

**Issue by rschwiebert** [mher/node-celery#43]
I'm using node v0.12.2  with celery 3.1.17 and redis for both the broker and backend.

I've slightly adapted this code from the examples directory:

var res = client.call('apps.encoding.panda_encoding.generate_thumbnails',
          [asset_uuid]);
setTimeout(function() {
       res.get(function(data) {
         console.log(data); // data will be null if the task is not finished
         client.end();
         client.broker.destroy();
       });
     }, 2000);

This results in an error inside of the redis module in the package. Adding logging inline, I think I've exposed the source of the unexpected token below. The lines beginning with "reply " mark where try_callback fired in the redis package: 

$ node myfile.js
reply # Server
[lots of server information omitted]

reply OK
reply �}q(childrenq]qXresultqcdjango.db.models.base
unpickle_inner_exception
qcflyweb_api.apps.flymedia.models
Asset
qX
  DoesNotExistq�qRX$Asset matching query does not exist.q	�q
bX	tracebackq
Traceback (most recent call last):
  File "/home/flyweb_api/www/venv/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/flyweb_api/www/venv/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/otherrepo/apps/encoding/thumbnails.py", line 74, in generate_thumbnails
    asset = Asset.objects.select_related('media').get(uuid=asset_uuid)
  File "/home/flyweb_api/www/venv/lib/python3.4/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
flyweb_api.apps.flymedia.models.DoesNotExist: Asset matching query does not exist.
q
XFAILUREqu.
/myrepo/apps/encoding/upload_lambda/node_modules/node-celery/node_modules/redis/index.js:603
                throw err;
                      ^
SyntaxError: Unexpected token �
    at Object.parse (native)
    at /myrepo/apps/encoding/upload_lambda/node_modules/node-celery/celery.js:320:32
    at try_callback (/myrepo/apps/encoding/upload_lambda/node_modules/node-celery/node_modules/redis/index.js:593:9)
    at RedisClient.return_reply (/myrepo/apps/encoding/upload_lambda/node_modules/node-celery/node_modules/redis/index.js:686:13)
    at ReplyParser.<anonymous> (/myrepo/apps/encoding/upload_lambda/node_modules/node-celery/node_modules/redis/index.js:321:14)
    at ReplyParser.emit (events.js:107:17)
    at ReplyParser.send_reply (/myrepo/apps/encoding/upload_lambda/node_modules/node-celery/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/myrepo/apps/encoding/upload_lambda/node_modules/node-celery/node_modules/redis/lib/parser/javascript.js:203:22)
    at RedisClient.on_data (/myrepo/apps/encoding/upload_lambda/node_modules/node-celery/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/myrepo/apps/encoding/upload_lambda/node_modules/node-celery/node_modules/redis/index.js:102:14)

I'm not sure what the right resolution to the problem is, but it does seem like a problem if every use ends in SyntaxError.

**Comment by rschwiebert** [comment]
Reading the open issues again, maybe this is a symptom of https://github.com/mher/node-celery/issues/15?

**Comment by hidetaka-f-matsumoto** [comment]
I faced a similar error.
In my case, the error occured at https://github.com/mher/node-celery/blob/master/celery.js#L320
It was because my celery worker process didn't serialize result to JSON.

So, I fixed celery worker code (python) as bellow, then the error was resolved.
tasks.py
```python
# -*- coding: utf-8 -*-
from celery import Celery

app = Celery('tasks', backend='redis://localhost', broker='amqp://')

# I fixed here ###
app.conf.update(
    CELERY_TASK_SERIALIZER='json',
    CELERY_RESULT_SERIALIZER='json',
)
##############

@app.task
def add(x, y):
    return x + y
```

Error detail:
```
SyntaxError: Unexpected token �
    at Object.parse (native)
    at /Users/xxx/Projects/SandBox/node.js.test/node_modules/node-celery/celery.js:322:32
    at try_callback (/Users/xxx/Projects/SandBox/node.js.test/node_modules/node-celery/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/Users/xxx/Projects/SandBox/node.js.test/node_modules/node-celery/node_modules/redis/index.js:685:13)
    at ReplyParser.<anonymous> (/Users/xxx/Projects/SandBox/node.js.test/node_modules/node-celery/node_modules/redis/index.js:321:14)
    at ReplyParser.emit (events.js:107:17)
    at ReplyParser.send_reply (/Users/xxx/Projects/SandBox/node.js.test/node_modules/node-celery/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/Users/xxx/Projects/SandBox/node.js.test/node_modules/node-celery/node_modules/redis/lib/parser/javascript.js:203:22)
    at RedisClient.on_data (/Users/xxx/Projects/SandBox/node.js.test/node_modules/node-celery/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/Users/xxx/Projects/SandBox/node.js.test/node_modules/node-celery/node_modules/redis/index.js:102:14)
```
