### ISSUE TITLE
TypeError: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by nzwade** [mher/node-celery#87]
When building on **Meteor 1.4.4.1** I hit the below error:

```
W20170423-15:12:38.332(1)? (STDERR) /Users/nzwade/.meteor/packages/meteor-tool/.1.4.4_1.1licv3w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170423-15:12:38.334(1)? (STDERR) 						throw(ex);
W20170423-15:12:38.334(1)? (STDERR) 						^
W20170423-15:12:38.334(1)? (STDERR) 
W20170423-15:12:38.335(1)? (STDERR) TypeError: Cannot read property 'slice' of null
W20170423-15:12:38.335(1)? (STDERR)     at new Configuration (/Volumes/storage partition/dev/project/project/project_meteor/node_modules/node-celery/celery.js:52:64)
W20170423-15:12:38.336(1)? (STDERR)     at new Client (/Volumes/storage partition/dev/project/project/project_meteor/node_modules/node-celery/celery.js:205:17)
W20170423-15:12:38.337(1)? (STDERR)     at Object.exports.createClient (/Volumes/storage partition/dev/project/project/project_meteor/node_modules/node-celery/celery.js:403:12)
W20170423-15:12:38.338(1)? (STDERR)     at meteorInstall.project_meteor.js (project_meteor.js:460:18)
W20170423-15:12:38.338(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170423-15:12:38.339(1)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170423-15:12:38.339(1)? (STDERR)     at /Volumes/storage partition/dev/project/project/project_meteor/.meteor/local/build/programs/server/app/app.js:1618:1
W20170423-15:12:38.340(1)? (STDERR)     at /Volumes/storage partition/dev/project/project/project_meteor/.meteor/local/build/programs/server/boot.js:303:34
W20170423-15:12:38.340(1)? (STDERR)     at Array.forEach (native)
W20170423-15:12:38.341(1)? (STDERR)     at Function._.each._.forEach (/Users/nzwade/.meteor/packages/meteor-tool/.1.4.4_1.1licv3w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
```
The code I have in Meteor to call node-celery is the same as the docs:
```
if (Meteor.isServer) {
var celery = require('node-celery'),
	client = celery.createClient({
		CELERY_BROKER_URL: 'amqp://guest:guest@localhost:5672//',
		CELERY_RESULT_BACKEND: 'amqp'
	});
...
```
It appears the error is triggered on line 52 of celery.js
`    self.backend_type = url.parse(self.RESULT_BACKEND).protocol.slice(0, -1);`
Why is this error happening despite specifying a RESULT_BACKEND when creating the client?

Thank you,

**Comment by nyxynyx** [comment]
Getting the same error with Meteor 1.4.4.1. http://stackoverflow.com/questions/43708795/using-meteor-with-node-celery-causes-error-cannot-read-property-slice-of-null

**Comment by p1nox** [comment]
I'm getting the same error, and I'm not even using Meteor:

```
self.backend_type = url.parse(self.RESULT_BACKEND).protocol.slice(0, -1);
                                                               ^

TypeError: Cannot read property 'slice' of null
```

**Comment by antoine-amara** [comment]
I had the same issue and I change the `CELERY_RESULT_BACKEND` option:

`CELERY_RESULT_BACKEND: 'amqp://'` and it works.

**Comment by mher** [comment]
Fixed by https://github.com/mher/node-celery/pull/89

**Comment by Goran-n** [comment]
This problem still exists, the fix below still works

> I had the same issue and I change the `CELERY_RESULT_BACKEND` option:
> 
> `CELERY_RESULT_BACKEND: 'amqp://'` and it works.
